---
- hosts: '10.250.14.1'
  become: True
  remote_user: "usuario de sistema"
  become_method: sudo
  become_user: root
  #vars:
  #ansible_become_password: "pw de sistema"  
  tasks:
    # - name: Generate key
    # openssh_keypair:
    # path: app
    - name: Create user
      user:
        name: app
        home: /home/app
        generate_ssh_key: no
    - name: Assert .ssh directory
      file:
        dest: /home/app/.ssh
        state: directory
        owner: app
        mode: '0700'
    - name: install public SSH key
      copy:
        src: app.pub
        dest: /home/app/.ssh/app.pub
        owner: app
        mode: '0600'
    - name: install authorized key
      authorized_key:
        user: app
        state: present
        key: "{{ lookup('file', 'app.pub') }}" 
